#!/usr/bin/env bash

# for git bash completion
# for more commands completion:
# http://stackoverflow.com/questions/9883851/why-git-ls-files-is-not-shown-on-tab-completion
# location: git/contrib/completion/git-completion.bash
[[ -r ~/.git-completion.bash ]] && source ~/.git-completion.bash

# for tmux bash completion
# location: tmux/examples/bash_completion_tmux.sh
[[ -r ~/.tmux-completion.bash ]] && source ~/.tmux-completion.bash

# setting python env
[[ -r ~/.pythonstartup ]] && export PYTHONSTARTUP="/home/kevin/.pythonstartup"

# for pyenv
if [[ -d "$HOME/.pyenv" ]]; then
    export PYENV_ROOT="$HOME/.pyenv"
    export PATH="$PYENV_ROOT/bin:$PATH"
    eval "$(pyenv init -)"

    # for pip completion
    eval "$(pip completion --bash)"
fi

# for rbenv
if [[ -d "$HOME/.rbenv" ]]; then
    export PATH="$HOME/.rbenv/bin:$PATH"
    eval "$(rbenv init -)"
fi

# for ruby related completion
[[ -r ~/.completion-ruby/completion-ruby-all ]] &&
             source ~/.completion-ruby/completion-ruby-all

# for nvm
if [[ -d "$HOME/.nvm" ]]; then
    source ~/.nvm/nvm.sh
    nvm use stable 1 > /dev/null
    [[ -r $NVM_DIR/bash_completion ]] && . $NVM_DIR/bash_completion

    # for npm completion
    eval "$(npm completion)"
fi

# for go
if [[ -d "$HOME/.goenv" ]]; then
    export PATH="$HOME/.goenv/bin:$PATH"
    eval "$(goenv init -)"
    export GOPATH="$HOME/work/go"
    export PATH=$PATH:$GOPATH/bin
fi

# vim:tw=78:ts=4:sw=4:sts=4:et:fdm=marker:ft=sh
